### ISSUE TITLE
案例展示后台管理

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#126]
案例展示部分，需要自己定义数据库模型，然后设计案例部分的后台管理。

你可能需要咨询 @wzl281158150  ，看看他那边需要哪些数据！

**Comment by ym13349140** [comment]
收到！

**Comment by xuelangZF** [comment]
代码的话，目前考虑是每个案例可以有若干版本的源码，每一个版本可能有多个源文件。

目前数据库设计是 Case 和 CaseCode, 每一个 Case 下面可以有许多CaseCode， CaseCode 以版本号区分。

**Comment by ym13349140** [comment]
师兄，每个版本下的源文件应该就直接在一个目录下吧，还有子目录之类的吗？

**Comment by xuelangZF** [comment]
子目录先不考虑吧

**Comment by xuelangZF** [comment]
这个实体是做什么用的？感觉这个实体有点多余，因为 CaseCode 中有一个字断就是描述版本的。

class CaseCodeMaterial(db.Model):
    """ 一个课时包括多种材料, 每个材料只能属于一个课时。 课时和材料是一对多的关系。
    """
    __tablename__ = 'case_code_materials'
    id = db.Column(db.Integer, primary_key=True)          # 资料 ID
    name = db.Column(db.String(1024), nullable=False)     # 资料名称
    uri = db.Column(db.String(256), default="")          # 资料路径
    case_id = db.Column(db.Integer, db.ForeignKey('cases.id'), nullable=False)
    version_id = db.Column(db.Integer, db.ForeignKey('case_codes.version_id'), nullable=False)

此外，代码库的管理也放进 “编辑” 进入后的页面吧，不要通过题目链接点进去。

**Comment by ym13349140** [comment]
这个是存放版本代码的表，没有这个的话，上传代码的时候就直接跳过数据库存到文件目录下吗？

**Comment by xuelangZF** [comment]
```
class CaseCode(db.Model):
    __tablename__ = "case_codes"

    case_id = db.Column(db.Integer, db.ForeignKey('cases.id'), nullable=False, primary_key=True)
    version_id = db.Column(db.Integer, nullable=False, primary_key=True)
    name = db.Column(db.String(256), nullable=False)
    description = db.Column(db.String(256), nullable=False)
    code_path = db.Column(db.String(64), nullable=False)
```

这个表中的 code_path 字段不是有记录代码的路径吗？

**Comment by xuelangZF** [comment]
```
class Case(db.Model):
    codes = db.relationship('CaseCode', backref='case', lazy='dynamic')

class CaseCode(db.Model):
```

我们这里要找某个代码文件，一般是通过 `case.codes` 来获取该案例下面所有代码，然后根据 version_id 来过滤不同版本的代码的。

代码的上传和删除，需要更新 CaseCode 的 `code_path` 字段。

**Comment by xuelangZF** [comment]
案例展示管理中，删除案例操作不成功。删除案例的版本库目录失败：

```
Traceback (most recent call last):
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/feizhao/dropbox/ehpc/eHPC/user/authorize.py", line 35, in wrap
    return func(*args, **kwargs)
  File "/Users/feizhao/dropbox/ehpc/eHPC/admin/system_views.py", line 228, in case_delete
    os.rmdir(path)
OSError: [Errno 66] Directory not empty: '/Users/feizhao/dropbox/ehpc/eHPC/static/case/2'
```

**Comment by xuelangZF** [comment]
上传案例版本代码失败！！

http://127.0.0.1:5000/admin/case/4/version/1/material/
