### ISSUE TITLE
程序边界、错误等意外情况的考虑

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#154]
很多地方需要考虑一些意外或者边界的情况，比如循环某个项目时，需要考虑万一该项目为空时，怎么处理。

这点在前端页面中特别常见，比如要对某个话题进行评论，需要考虑当前用户是否登录（甚至是否有权限评论，我们目前只要登录就可以评论的）。要没有登陆时，下面评论框如何显示。

在比如课程的评价，如果当前没有评论，该如何显示？（目前做法还可以）

![image](https://cloud.githubusercontent.com/assets/2769831/20916550/4c028278-bbc7-11e6-9950-5d75c0328098.png)

**Comment by xuelangZF** [comment]
比如 @ym13349140  的 case_upload 视图函数中，有以下代码：

```
status = upload_file(material, os.path.join(current_app.config['CASE_FOLDER'], material_uri))
return render_template('admin/case/upload.html')
```

并没有判断 upload_file 是否上传成功，就继续往下操作。导致文件显示上传成功， 但是其实并没有存到服务器上。

**Comment by xuelangZF** [comment]
案例展示中，如果后台没有数据库记录的版本中的代码文件，目前是前端点击代码后根本没反应，后台会有下面的提示：

```shell
Traceback (most recent call last):
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/feizhao/dropbox/ehpc/eHPC/case/views.py", line 39, in show_case
    with open(path, 'r') as code:
IOError: [Errno 2] No such file or directory: u'/Users/feizhao/dropbox/ehpc/eHPC/static/case/6/version_1/test_loadsetting.py'
```

更好的做法是，读后台文件失败时，返回一个信息，然后前台点击相应的文件后，给出“访问的文件意外被删除，请联系管理员” 之类的提示信息。  @wzl281158150 这里改一下吧。

**Comment by wzl281158150** [comment]
收到

**Comment by wzl281158150** [comment]
师兄，这个你直接改一下吧。。就多3行代码
case/views.py里的show_case函数
···python
with open(path, 'r') as code:
···
改成，也就是加如一个try except结构即可
···python
try:
                    with open(path, 'r') as code:
                        return jsonify(status='success', code=code.read())
                except IOError:
                    return jsonify(status='fail')
···

**Comment by xuelangZF** [comment]
OK，没问题。我来修复

**Comment by xuelangZF** [comment]
https://github.com/xuelangZF/ehpc/issues/194 中提到的 Bug 也是没有考虑到各种情况。

**Comment by xuelangZF** [comment]
https://github.com/xuelangZF/ehpc/issues/230  缺少对表单进行验证。
