### ISSUE TITLE
试题中心题目浏览失败

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#210]
http://a002.nscc-gz.cn:10165/problems/question/  中，并行默认题库添加了 200 多道题目，**开始做题**－－**选择题** 会出错。

错误日志如下：

```shell
[2016-12-22 23:46:51 +0000] [3586] [ERROR] Error handling request /problems/question/choice/5/
Traceback (most recent call last):
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 52, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 152, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 103, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/home/netlab513/ehpc/eHPC/problem/views.py", line 104, in question_view
    q_type=question_type)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/netlab513/ehpc/eHPC/templates/problem/practice_detail.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/netlab513/ehpc/eHPC/templates/base.html", line 15, in top-level template code
    {% block content %}
  File "/home/netlab513/ehpc/eHPC/templates/problem/practice_detail.html", line 73, in block "content"
    {% include 'problem/widget_choice_detail.html' %}
  File "/home/netlab513/ehpc/eHPC/templates/problem/widget_choice_detail.html", line 24, in top-level template code
    {% include 'course/widget_paper_question_detail.html' %}
  File "/home/netlab513/ehpc/eHPC/templates/course/widget_paper_question_detail.html", line 3, in top-level template code
    {% include 'course/widget_paper_choice_options.html' %}
  File "/home/netlab513/ehpc/eHPC/templates/course/widget_paper_choice_options.html", line 7, in top-level template code
    <span>{{ choice.content | get_json_value(i | string) }}</span>
  File "/home/netlab513/ehpc/eHPC/util/admin_filter.py", line 10, in get_json_value
    return json.loads(text)[key]
KeyError: u'0'
```

@wzl281158150  来修复。

另外试题中心部分，模版中有大量 style 写死的样式，很容易导致样式显示出问题，比如判断题，前面就有多余的空白。

![image](https://cloud.githubusercontent.com/assets/2769831/21431336/c8a6db94-c8a1-11e6-9a79-860febf8c4b0.png)

建议好好设计页面的布局，用 class 来设置不同content的 padding 和 margin，而不是手动去调整细小的位置。

**Comment by wzl281158150** [comment]
师兄，请问导入的题目怎么获得？

**Comment by xuelangZF** [comment]
给了你服务器账户、密码了，你可以直接查看数据库内容。

**Comment by xuelangZF** [comment]
关于 CSS 整个布局的问题，我之前在 https://segmentfault.com/q/1010000000178043  中提过问题，然后 [@nightire](https://github.com/nightire) 的回答特别中肯：

> padding-top 直接加给 body 而不是标题即可；你应当把页面全体（除了置顶的 navbar 以外）看做一个“容器”，而不是因为看到标题被遮住就以为只是标题出了问题。头疼医头，脚疼医脚的视野和观念是永远也写不出优雅的 CSS 的（同理适用各种语言……）。

希望更改后的代码优雅、易读！
