### ISSUE TITLE
创建作业时有空余字段，前端无提示信息

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#230]
在创建作业时，如果标题和截止时间没有填写，前台并不会给出提示。后台会出错！

时间没有填写：

```python
127.0.0.1 - - [29/Dec/2016 20:32:54] "POST /admin/course/1/homework/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/feizhao/dropbox/ehpc/eHPC/user/authorize.py", line 45, in wrap
    return func(*args, **kwargs)
  File "/Users/feizhao/dropbox/ehpc/eHPC/admin/teacher_views.py", line 289, in course_homework
    deadline = datetime.strptime(request.form['deadline'], '%Y-%m-%d %H:%M')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y-%m-%d %H:%M'
```

标题没有填写：

```python
127.0.0.1 - - [29/Dec/2016 20:38:24] "POST /admin/course/1/homework/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/feizhao/dropbox/ehpc/eHPC/user/authorize.py", line 45, in wrap
    return func(*args, **kwargs)
  File "/Users/feizhao/dropbox/ehpc/eHPC/admin/teacher_views.py", line 289, in course_homework
    deadline = datetime.strptime(request.form['deadline'], '%Y-%m-%d %H:%M')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: :19
```

@ym13349140  需要看下时间输入插件的文档，看它如何对时间段进行验证。至于标题段，可以在标签中加 required 即可。

luozhx  的时间输入也有同样的 Bug，你帮他修复一下吧。

**Comment by ym13349140** [comment]
师兄，我在修改我这边作业查看逻辑的时候点击了推出可乘，然后发现那个加入课程的部分好像有点问题，如果学生主动点击“退出课程”按钮后再刷新页面，那个按钮就变成了“加入审批中”，但是后台显示的是已经加入了，所以就导致用户没办法再加入课程了。
![image](https://cloud.githubusercontent.com/assets/17507937/21558417/7f7b8efa-ce74-11e6-85af-65bcaf58f256.png)
![image](https://cloud.githubusercontent.com/assets/17507937/21558419/8deeeafe-ce74-11e6-8d05-1c825cd06215.png)

**Comment by xuelangZF** [comment]
确实是，厉害！捉 Bug 大师，哈哈

**Comment by xuelangZF** [comment]
下次发现问题直接开 issue 说哈，这次我帮你开一个吧

**Comment by ym13349140** [comment]
好的~

**Comment by xuelangZF** [comment]
👌 

表单验证其实是个值得深入去挖的地方。有许多比较成熟的表单验证库，你有余力的话，可以看看哈。

HTML5 中在表单中字段加入 required ，浏览器也会检查这个字断的，有时候可以节省代码，不用那么麻烦的写一堆代码去验证每个字断。

**Comment by ym13349140** [comment]
我一开始是用的required，然后发现没有效果，因为required字段只有在表单直接提交到action的时候才能起作用，但是作业创建那里用的是Ajax提交到后台，所以required没有用，我才用的JS来判断。有空我去看看表单验证部分~

**Comment by xuelangZF** [comment]
哦哦哦， soga，我以为 ajax 也有效果呢。长知识！

你的 js 判断做的不错，下面的提示信息很棒的！

**Comment by ym13349140** [comment]
刚刚说到required，我去看了一眼课程信息编辑的那里好像用的就是required，然后发现没有课程标题也能保存成功。

**Comment by xuelangZF** [comment]
估计很多表单都没验证。。。。看来是时候上表单验证的 js 库了。另开issue 说
