### ISSUE TITLE
虚拟桌面连接一级代理失败

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#355]
部署在服务器上的虚拟桌面连接失败。

用超算域名的话，错误Log 如下：

```
ConnectionError: HTTPConnectionPool(host='a002.nscc-gz.cn', port=10231): Max retries exceeded with url: /server/controller?This_is_a_very_secret_token=8zZStohCumaeHv71i0TLnK93ODGkwYRd&user_id=3 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4ef13f9490>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/netlab513/ehpc/eHPC/util/email.py", line 14, in send_async_email
    mail.send(msg)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask_mail.py", line 156, in configure_host
    host = smtplib.SMTP_SSL(self.mail.server, self.mail.port)
  File "/usr/lib/python2.7/smtplib.py", line 788, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 793, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gevent/socket.py", line 64, in create_connection
    for res in getaddrinfo(host, port, 0 if has_ipv6 else AF_INET, SOCK_STREAM):
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gevent/_socketcommon.py", line 268, in getaddrinfo
    return get_hub().resolver.getaddrinfo(host, port, family, socktype, proto, flags)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gevent/resolver_thread.py", line 64, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gevent/pool.py", line 300, in apply
    return self.spawn(func, *args, **kwds).get()
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gevent/event.py", line 373, in get
    return self.get(block=False)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gevent/event.py", line 363, in get
    return self._raise_exception()
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gevent/event.py", line 343, in _raise_exception
    reraise(*self.exc_info)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gevent/threadpool.py", line 207, in _worker
    value = func(*args, **kwargs)
gaierror: [Errno -2] Name or service not known
```

直接用内网地址的话，Log 如下：

```
[2017-03-13 10:35:24 +0000] [13737] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 62, in handle
    six.reraise(*sys.exc_info())
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 52, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 152, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 125, in handle_request
    six.reraise(*sys.exc_info())
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 103, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/home/netlab513/ehpc/eHPC/lab/views.py", line 175, in vnc
    "user_id": current_user.id})
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/requests/sessions.py", line 603, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/requests/sessions.py", line 685, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '10.174.5.23:8080/server/controller'

[2017-03-13 10:36:51 +0000] [13785] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 62, in handle
    six.reraise(*sys.exc_info())
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 52, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 152, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 125, in handle_request
    six.reraise(*sys.exc_info())
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 103, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/home/netlab513/ehpc/eHPC/lab/views.py", line 175, in vnc
    "user_id": current_user.id})
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/requests/sessions.py", line 603, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/requests/sessions.py", line 685, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '10.133.100.145:8080/server/controller'
```

@wzl281158150

**Comment by xuelangZF** [comment]
此外，请注意将 代理服务器IP和端口号 写在**配置文件**中！！ 不要在代码中硬编码配置。
