### ISSUE TITLE
文件管理部分Bug！

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#391]
课程的后台管理部分，有的课程会删除不了！原因：服务器resource目录中课程资源缺失。导致某些删文件和目录的操作**抛出异常**，后续操作无法完成。

```
127.0.0.1 - - [21/Mar/2017 20:42:43] "POST /admin/course/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/feizhao/dropbox/ehpc/eHPC/user/authorize.py", line 45, in wrap
    return func(*args, **kwargs)
  File "/Users/feizhao/dropbox/ehpc/eHPC/admin/teacher_views.py", line 36, in course
    os.remove(os.path.join(current_app.config['RESOURCE_FOLDER'], m.uri))
OSError: [Errno 2] No such file or directory: '/Users/feizhao/dropbox/ehpc/eHPC/static/resource/course_15/lesson139_material244.pdf'
```

本地测试 删除 云计算概论即可复现这个 Bug。

@luozhx

**Comment by xuelangZF** [comment]
改进意见：封装所有用到的文件操作函数。

比如删除一个实体时，如果对应的有删除文件系统上面的文件，那么调用我们封装好的删除操作。（首先判断是否存在要删除的文件，如果不存在则直接忽略。存在的话，则删除，如果删除仍然抛出异常，需要指定异常处理过程。）

**Comment by xuelangZF** [comment]
**删除数据库中多余的表格？**

paper_course 记录的是课程和其对应的测验吧，你确定这个没用？

**Comment by xuelangZF** [comment]
![image](https://cloud.githubusercontent.com/assets/2769831/24192606/801f0eda-0f2a-11e7-91c6-cff1d5f45dd5.png)

这里删除了 `os.remove(os.path.join(current_app.config['RESOURCE_FOLDER'], m.uri))` 这一句是什么意思？**课时材料 PDF 文件在后台不用删除了？**

我的意思是，对这种删除操作，我们不要直接用  os.remove 来。因为这个函数会在文件不存在时抛出异常的。我们需要封装一个删除文件的函数，类似下面这样对删除一系列目录的封装：

```
def remove_dirs(*dir_paths):
    """ 删除参数里面列出的所有的目录

    如果目录不存在, 不给出任何提示, 直接忽略。
    删除目录 path_1, path_2, path_3, 可以用下面操作:

        remove_dirs(path_1, path_2, path_3)
    """
    for one_dir in dir_paths:
        shutil.rmtree(one_dir, True)
```

**Comment by luozhx** [comment]
course和paper是一对多关系，不是多对多关系，是不需要增加一张表格来记录关系的。
在paper的表格里已经有course的id作为外键来建立关系。
![test](https://cloud.githubusercontent.com/assets/22886929/24193046/dbeac2bc-0f2b-11e7-8bbb-c7e6b6ade24b.png)

删除`os.remove(os.path.join(current_app.config['RESOURCE_FOLDER'], m.uri))`是因为在后面会有
`remove_dirs(resource_path, homework_path, homework_appendix_path, cover_path)`可以将整个资源文件夹删除，所以PDF资源不需要先删除。

**Comment by xuelangZF** [comment]
Soga，完全明白了。Sorry，之前没有细看。

**Comment by xuelangZF** [comment]
还是有错误。  本地删除并行计算课  可以复现Bug。错误原因是 删除顺序出错，数据库记录无法删除。

```
Traceback (most recent call last):
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/feizhao/dropbox/ehpc/eHPC/user/authorize.py", line 45, in wrap
    return func(*args, **kwargs)
  File "/Users/feizhao/dropbox/ehpc/eHPC/admin/teacher_views.py", line 46, in course
    for c in curr_course.comments:
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/orm/dynamic.py", line 243, in __iter__
    sess = self.session
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/orm/dynamic.py", line 235, in session
    sess.flush()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 561, in execute
    uow
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 249, in delete_obj
    cached_connections, mapper, table, delete)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 892, in _emit_delete_statements
    c = connection.execute(statement, del_objects)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _execute_context
    context)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 95, in do_executemany
    rowcount = cursor.executemany(statement, parameters)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/MySQLdb/cursors.py", line 237, in executemany
    r = r + self.execute(query, a)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (_mysql_exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`ehpc`.`paper_course`, CONSTRAINT `paper_course_ibfk_2` FOREIGN KEY (`paper_id`) REFERENCES `papers` (`id`))') [SQL: u'DELETE FROM papers WHERE papers.id = %s'] [parameters: ((1L,), (2L,), (3L,))]
```

@luozhx

**Comment by luozhx** [comment]
IntegrityError: (_mysql_exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`ehpc`.`paper_course`, CONSTRAINT `paper_course_ibfk_2` FOREIGN KEY (`paper_id`) REFERENCES `papers` (`id`))') [SQL: u'DELETE FROM papers WHERE papers.id = %s'] [parameters: ((1L,), (2L,), (3L,))]
这个是数据库里面的paper_course这张表没有删除吧，这个要先手动删除

**Comment by xuelangZF** [comment]
ok，晓得了。
