### ISSUE TITLE
超算接口问题？

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#396]
目前超算接口通过公网域名访问时主要存在下面两个问题：

1. 接口不够稳定，时不时的“上传文件失败”。
2. 异步获取程序运行结果，需要去请求多次才能拿到结果。时延有5秒左右。

@lijiang2014 @Zouzhp3 

这里是用公网域名访问，如果直接用内网地址访问的话，不知道延时怎么样。  
https://github.com/xuelangZF/ehpc/issues/397

**Comment by lijiang2014** [comment]
这个5s 是指从提交完开始计时还是跑完作业开始计时还是只是下载文件花费的时间？

**Comment by xuelangZF** [comment]
是从提交作业到获取到结果的时延。当然目前只用了很小的程序，跑作业本身耗不了多少时间。

**Comment by lijiang2014** [comment]
这个因为涉及到了排队，目前的架构是会比较花费时间。
如果要解决这个问题，可以通过预先占据节点的方式来进行作业的提交，不过需要自己维护一个作业队列，系统会复杂一些。

**Comment by xuelangZF** [comment]
现在登录出现新的问题，Log 如下：

```
127.0.0.1 - - [26/Mar/2017 21:15:02] "POST /lab/knowledge/5/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Users/feizhao/dropbox/ehpc/eHPC/lab/views.py", line 119, in knowledge
    is_success[0] = client.login()
  File "/Users/feizhao/dropbox/ehpc/eHPC/util/code_process.py", line 124, in login
    self.login_cookie = 'newt_sessionid=' + tmpdata["output"]["newt_sessionid"]
TypeError: string indices must be integers, not str
```
