### ISSUE TITLE
虚拟实验室接口适配问题？

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#398]
虚拟实验室中提交程序，运行成功后，获取结果进行显示时，会出问题，Log如下：

```
jump to async
jump to async
jump to async
jump to async
127.0.0.1 - - [22/Mar/2017 17:52:22] "POST /lab/knowledge/5/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Users/feizhao/dropbox/ehpc/eHPC/lab/views.py", line 130, in knowledge
    task_number, cpu_number_per_task, node_number)
  File "/Users/feizhao/dropbox/ehpc/eHPC/util/code_process.py", line 277, in ehpc_run
    cpu_number_per_task=cpu_number_per_task, partition=partition)
  File "/Users/feizhao/dropbox/ehpc/eHPC/util/code_process.py", line 239, in submit_job
    return tmpdata["output"]["jobid"]
TypeError: string indices must be integers
```

应该是对输出的读取部分还有 Bug。

@Zouzhp3

**Comment by Zouzhp3** [comment]
这个问题是：虽然代码编译已经成功，但是在天河系统加入任务队列时出错，导致没有返回的是错误信息而不是 jobid ，所以获取就失败了。这段代码本身是没有问题的。

**Comment by xuelangZF** [comment]
虚拟实验室的程序一直都是这种情况，为什么会一直加入任务队列时出错呢？

在线编程的出现这种情况比较少

**Comment by Zouzhp3** [comment]
现在试了下又可以了。

![1490188100 1](https://cloud.githubusercontent.com/assets/22606175/24199290/f58734d6-0f43-11e7-99dc-4c93b5161e25.jpg)

加入任务队列出错是天河系统那边的问题，因为加入任务队列出错时，天河系统返回的值如下：

`{u'status': u'ERROR', u'output': u'', u'error': u'qsub failed with error: sbatch: error: Batch job submission failed: Required partition not available (inactive or drain)\n', u'status_code': 500}`

而正常情况下天河的返回值是：`{u'status': u'OK', u'output': {u'jobid': u'5011965'}, u'error': u'', u'status_code': 200}`

**Comment by lijiang2014** [comment]
Batch job submission failed: Required partition not available (inactive or drain)\n
这个问题是当前作业队列不可用导致的。一般是整个环境在进行维护或管理员对故障的临时处理。
