### ISSUE TITLE
更换HPC主机后无法提交程序

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#446]
更新后 https://github.com/xuelangZF/ehpc/pull/441，出现下面的问题：

```
[2017-04-12 16:44:51 +0000] [5141] [ERROR] Error handling request /lab/knowledge/5/
Traceback (most recent call last):
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 52, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 152, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 103, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/home/netlab513/ehpc/eHPC/lab/views.py", line 139, in knowledge
    task_number, cpu_number_per_task, node_number)
  File "/home/netlab513/ehpc/eHPC/util/code_process.py", line 284, in ehpc_run
    cpu_number_per_task=cpu_number_per_task, partition=partition)
  File "/home/netlab513/ehpc/eHPC/util/code_process.py", line 243, in submit_job
    return tmpdata["output"]["jobid"]
TypeError: string indices must be integers
``` 

这个错误不知道是什么原因？

**Comment by xuelangZF** [comment]
这个错误出现过很多次，具体原因可能包括
1）超算中心开启了两个不同版本的API接口，导致其中一个返回和现在的实现不一样，这种情况下可能同一份代码会返回不同的结果；
2）slurm系统不稳定，具体的问题李江也没有告诉过我；
3）我们这边实现有误；

对于1）如果隔一段时间试一试又返回正确结果就是这个错误，但是我刚刚测试好像不会出现这个错误；
对于2）玄学错误，我也不是很清楚；
对于3）比起以前我没有修改这个部分，只修改了分区名，如果出错的话错误不会是这个。

**Comment by milanlanlan** [comment]
发现错误了，是我写错了，问题出现在判断node_number和TH2_MAX_NODE_NUMBER的大小的地方。
我在测试的时候是直接令 node_number = 1，是int型，所以可以正常运行。但是部署到服务器的时候node_number是一个string型的参数，所以出错了，我没有考虑到这个问题。

解决方案：
在../util/code_process.py文件的第230-231行和280-281行：

```
if node_number > TH2_MAX_NODE_NUMBER :
            partition = "BIGJOB1"
```

修改成

```
if int(node_number) > TH2_MAX_NODE_NUMBER :
            partition = "BIGJOB1"
```

是我写的测试文件有问题造成这次bug，不是超算方面的问题。
