### ISSUE TITLE
程序中带有中文无法运行

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#470]
在线编程和虚拟实验部分，代码中如果有中文字符，就会出错：

在线编程 Log：

```
[2017-04-24 15:29:06,813] ERROR in app: Exception on /problems/2/submit/ [POST]
Traceback (most recent call last):
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/home/zhao/ehpc/eHPC/problem/views.py", line 164, in submit
    task_number=task_number, cpu_number_per_task=cpu_number_per_task, node_number=node_number, language=language)
  File "/home/zhao/ehpc/eHPC/util/code_process.py", line 333, in submit_code
    is_success[0] = client.upload(TH2_MY_PATH, input_filename, source_code)
  File "/home/zhao/ehpc/eHPC/util/code_process.py", line 180, in upload
    tmpdata = self.open("/file/" + TH2_MACHINE_NAME + myPath + '/' + filename, method="PUT", data=data)
  File "/home/zhao/ehpc/eHPC/util/code_process.py", line 56, in open
    resp = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1181, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 868, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 840, in send
    self.sock.sendall(data)
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/gevent/_socket2.py", line 373, in sendall
    data = data.encode()
UnicodeEncodeError: 'ascii' codec can't encode characters in position 294-301: ordinal not in range(128)
```

虚拟实验室Log：

```
[2017-04-24 16:07:39,955] ERROR in app: Exception on /lab/knowledge/5/ [POST]
Traceback (most recent call last):
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/home/zhao/ehpc/eHPC/lab/views.py", line 129, in knowledge
    is_success[0] = client.upload(myPath, input_filename, source_code)
  File "/home/zhao/ehpc/eHPC/util/code_process.py", line 180, in upload
    tmpdata = self.open("/file/" + TH2_MACHINE_NAME + myPath + '/' + filename, method="PUT", data=data)
  File "/home/zhao/ehpc/eHPC/util/code_process.py", line 56, in open
    resp = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1181, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 868, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 840, in send
    self.sock.sendall(data)
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/gevent/_socket2.py", line 373, in sendall
    data = data.encode()
UnicodeEncodeError: 'ascii' codec can't encode characters in position 138-139: ordinal not in range(128)
```

**Comment by milanlanlan** [comment]
应该改成 utf8 编码就可以了，请在对应 views.py 文件中加入以下代码尝试一下：
```
import sys  
reload(sys)  
sys.setdefaultencoding('utf8')   
```

此外，之前的服务器似乎登录不进去了，我目前也没办法调试。

**Comment by xuelangZF** [comment]
改 UTF-8 编码也不是在这里这样改的。  算了，我来改吧。

**Comment by milanlanlan** [comment]
好的，不过我记得以前的话如果把全部程序都改成 utf-8 好像也会出一些问题，此外也可能改了utf-8编码还会出问题，（好像是由于在request中转码会出问题，也可能是我记错了）可以注意一下这些。

**Comment by xuelangZF** [comment]
[urllib2.Request](https://docs.python.org/2/library/urllib2.html#urllib2.Request) 类的data数据为：

```
data may be a string specifying additional data to send to the server, or None if no such data is needed. Currently HTTP requests are the only ones that use data; the HTTP request will be a POST instead of a GET when the data parameter is provided. data should be a buffer in the standard application/x-www-form-urlencoded format. The urllib.urlencode() function takes a mapping or sequence of 2-tuples and returns a string in this format.
```

当上传代码时，data 保存了默认的代码文本，并且为 unicode 类型，需要显式将其编码（采用 utff-8）。

```
        if data:
            try:
                data = urllib.urlencode(data)
            except TypeError:
                data = data.encode('utf-8')             # Issue 470

            # https://docs.python.org/2/library/urllib2.html#urllib2.Request
            # Data may be a string specifying additional data to send to the server
            req = urllib2.Request(url, data)
        else:
            req = urllib2.Request(url)
```

**Comment by milanlanlan** [comment]
好的，明白了
