### ISSUE TITLE
邮件日志文件混杂其他信息

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#473]
python 的 logging 是允许在一个项目中，生成多个 log 文件，并且每个 log 记录不同的信息。

目前我们的邮件 log 文件中，混杂了其他错误信息，比如：

```
AttributeError: 'NoneType' object has no attribute 'visitNum'
[2017-04-25 09:58:05,057] Exception on /problems/1/submit/ [POST]
Traceback (most recent call last):
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/home/zhao/ehpc/eHPC/problem/views.py", line 164, in submit
    task_number=task_number, cpu_number_per_task=cpu_number_per_task, node_number=node_number, language=language)
  File "/home/zhao/ehpc/eHPC/util/code_process.py", line 329, in submit_code
    is_success[0] = client.login()
  File "/home/zhao/ehpc/eHPC/util/code_process.py", line 124, in login
    self.login_cookie = 'newt_sessionid=' + tmpdata["output"]["newt_sessionid"]
TypeError: string indices must be integers, not str
```

或者是 

```
[2017-04-25 04:38:48,132] Exception on /article/4 [GET]
Traceback (most recent call last):
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zhao/.Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zhao/ehpc/eHPC/article/views.py", line 20, in detail
    detail_article.visitNum += 1
AttributeError: 'NoneType' object has no attribute 'visitNum'
```

请完善 log 系统，确保email 的log只记录 邮件发送日志。

**Comment by xuelangZF** [comment]
目前日志中不再混杂有其他信息了。
