### ISSUE TITLE
并行程序调用超算提供接口

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#99]
并行程序和超算那边对接，实现简单的上传一个代码文本和编译命令到超算，然后获取超算的运算结果，进行展示。

使用 requests 库和超算进行数据传输。

建议将主要过程**抽象为你方便使用的接口**，然后在 Flask view 中直接调用接口。比如 util/file_manage.py 里面的 `def upload_img(file_src, des_height, des_width, des_path)` 接口用于上传文件。

@milanlanlan  看到后请在下面回复是否 Get

**Comment by milanlanlan** [comment]
get

**Comment by xuelangZF** [comment]
@milanlanlan  现在是什么进度了

**Comment by xuelangZF** [comment]
看了你的提交，程序有明显的语法错误！

1. 用 "%S"  来表示字符串
2. 有很多地方使用了 machine_name，但是都没有看到它的定义的地方。  Pycharm 直接 标红显示这个地方有问题！！！

```
# GET /api/file/<machine>/<path>列目录
 	#那边没有给输出,暂时不用
 	def get_directory(self, path):
 		tmpdata = self.open("/file/" + machine_name + path + '/')
 		return self.ret200()
 ```

希望下次不要再来这么一些明显的错误！

认真对待你的提交！

**Comment by xuelangZF** [comment]
放在服务器上，没法提交代码。。http://a002.nscc-gz.cn:10165/problems/program/4/ 你可以去试试。

**Comment by xuelangZF** [comment]
错误日志如下：

```
[2016-12-02 23:27:42 +0000] [1453] [ERROR] Error handling request /problems/4/submit/
Traceback (most recent call last):
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 52, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 152, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 103, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/netlab513/Envs/ehpc/local/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/home/netlab513/ehpc/eHPC/problem/views.py", line 132, in submit
    is_success = client.upload(path, input_filename, source_code)
  File "/home/netlab513/ehpc/eHPC/problem/code_process.py", line 177, in upload
    tmpdata = self.open("/file/" + machine_name + path + '/' + filename, method="PUT", data=data)
  File "/home/netlab513/ehpc/eHPC/problem/code_process.py", line 109, in open
    self.status_code = resp.getcode()
UnboundLocalError: local variable 'resp' referenced before assignment
```

**Comment by xuelangZF** [comment]
我改了一下代码了，现在可以跑通，但是传代码失败，所以编译不通过，输出看起来是这样子的：

```
g++: code/2_1.c: No such file or directory
g++: no input files
```

运行了你的本地测试，结果如下：

```
(ehpc) netlab513@ubuntu:~/ehpc/eHPC/problem$ python code_process.py
upload fail.
jump to async
jump to async
Compiler:  Compile success.
Run     :  0
```

这块还是有问题，你好好再和超算那边沟通下。

**Comment by xuelangZF** [comment]
另外，我不知道为什么 ehpc_client 需要那么多接口，像下面的接口我们貌似并不需要：

```
   def get_directory(self, path):
        self.open("/file/" + machine_name + path + '/')
        return self.ret200()

    # GET /api/async/<id>获取
    def get_file(self, file_id):
        tmpdata = self.open(async_url + '/' + file_id)
        if self.ret200():
            return tmpdata["output"]["output"]
        else:
            return None
```

你首先需要理清楚到底需要哪些接口？比如：

* 传代码给服务器？
* 发送编译命令给服务器？
* 接受服务器的反馈信息？

**Comment by xuelangZF** [comment]
另外，使用 `urllib2` 库来做网络请求其实不是很方便，Python 有一个封装好的网络请求库 [requests](http://docs.python-requests.org/en/master/)，使用特别方便。支持 session ，登录完之后，之后的 get, post 请求会自动带 cookie， 不需要额外处理 cookie 相关的信息。

[一步步爬取Coursera课程资源](http://selfboot.cn/2014/09/03/how_to_crawl_coursera/) 简单说了 requests 库的操作。

**Comment by xuelangZF** [comment]
上周的接口问题，他们那边什么反馈？ @milanlanlan
